language:  generic

notifications:
  slack:
    rooms:
      - apacheexpress:9z2IfvxZfENp0TFmiYCgyUKz

matrix:
    include:
        - os:   osx
          osx_image: xcode10.2

before_install:
    - brew update
    - brew install swiftxcode/swiftxcode/swift-xcode

script:
    - make
